/**
 * Static seed data — used for dev/preview rendering before Supabase is configured.
 * Also consumed by the /api/seed route and the seed script.
 */
import type { Game, User, Score, Challenge, LeaderboardEntry } from '@/types'

export const SEED_GAMES: Game[] = [
  {
    id: '1',
    slug: 'flappy-stokes',
    title: 'Flappy Stokes',
    description: 'Dodge the obstacles as Alex or Alan. One tap. No mercy.',
    thumbnailUrl: '/images/twins-flappy-birds-50pct.jpg',
    embedUrl: '/games/built-in/flappy-stokes',
    categories: ['SPEED'],
    stokesScore: 91,
    alexRating: 4.5,
    alanRating: 5.0,
    alexReview: 'This game is actually hard lol',
    alanReview: "I got 47 on my first try. Beat that.",
    fanScore: 89,
    totalPlays: 142_400,
    activePlayers: 312,
    badges: ['TWIN_PICK', 'EXCLUSIVE'],
    isInstantPlay: true,
    isMobile: true,
    isActive: true,
    isExclusive: true,
    maxScore: 9999,
    releaseDate: '2024-01-15',
    createdAt: '2024-01-15T00:00:00Z',
    type: 'builtin',
  },
  {
    id: '2',
    slug: 'twin-trivia',
    title: 'Twin Trivia',
    description: '100+ questions on Gen-Z culture, Stokes Twins, world facts and more. New questions every game!',
    thumbnailUrl: '/images/twins-scoreboard-50pct.jpg',
    embedUrl: '/games/built-in/twin-trivia',
    type: 'builtin',
    categories: ['STRATEGY'],
    stokesScore: 78,
    alexRating: 4.0,
    alanRating: 4.0,
    alexReview: 'Some of these questions are HARD. We got most of them right tho.',
    alanReview: 'Alex barely passed. I got a perfect score.',
    fanScore: 82,
    totalPlays: 87_200,
    activePlayers: 145,
    badges: ['HOT', 'TWIN_PICK'],
    isInstantPlay: true,
    isMobile: true,
    isActive: true,
    isExclusive: false,
    maxScore: 2250,
    releaseDate: '2024-02-01',
    createdAt: '2024-02-01T00:00:00Z',
  },
  {
    id: '3',
    slug: 'stokes-runner',
    title: 'Stokes Runner',
    description: 'Infinite side-scroller. Run, jump, survive. How far can you go?',
    thumbnailUrl: '/images/twins-jungle-50pct.jpg',
    embedUrl: '/games/built-in/stokes-runner',
    type: 'builtin',
    categories: ['SPEED', 'CHAOTIC'],
    stokesScore: 85,
    alexRating: 5.0,
    alanRating: 4.5,
    alexReview: "I literally cannot stop playing this. Send help.",
    alanReview: 'Alex has a problem. The game is great though.',
    fanScore: 88,
    totalPlays: 203_800,
    activePlayers: 489,
    badges: ['HOT', 'NEW'],
    isInstantPlay: true,
    isMobile: true,
    isActive: true,
    isExclusive: false,
    maxScore: 999999,
    releaseDate: '2024-03-01',
    createdAt: '2024-03-01T00:00:00Z',
  },
  {
    id: '4',
    slug: 'face-dodge',
    title: 'Face Dodge',
    description: "Dodge falling objects, collect power-ups. Don't let them hit your face.",
    thumbnailUrl: '/images/twins-facedodge.png',
    embedUrl: '/games/built-in/face-dodge',
    type: 'builtin',
    categories: ['CHAOTIC'],
    stokesScore: 72,
    alexRating: 3.5,
    alanRating: 4.0,
    alexReview: 'Fun chaos. Gets insane fast.',
    alanReview: 'Very chaotic. I love it.',
    fanScore: 75,
    totalPlays: 54_100,
    activePlayers: 76,
    badges: ['NEW'],
    isInstantPlay: true,
    isMobile: true,
    isActive: true,
    isExclusive: false,
    maxScore: 50000,
    releaseDate: '2024-03-10',
    createdAt: '2024-03-10T00:00:00Z',
  },
  {
    id: '5',
    slug: 'twin-reaction',
    title: 'Twin Reaction',
    description: 'Reaction time challenge. Tap when prompted. Faster than the twins?',
    thumbnailUrl: '/images/twins-tnt-50pct.jpg',
    embedUrl: '/games/built-in/twin-reaction',
    type: 'builtin',
    categories: ['SPEED'],
    stokesScore: 80,
    alexRating: 4.0,
    alanRating: 4.5,
    alexReview: 'My reaction time is elite. Alan disagrees.',
    alanReview: 'I am FASTER. The numbers prove it.',
    fanScore: 79,
    totalPlays: 38_600,
    activePlayers: 54,
    badges: ['CHALLENGE'],
    isInstantPlay: true,
    isMobile: true,
    isActive: true,
    isExclusive: false,
    maxScore: 1000,
    releaseDate: '2024-02-20',
    createdAt: '2024-02-20T00:00:00Z',
  },
  {
    id: '6',
    slug: 'stokes-snake',
    title: 'Stokes Snake',
    description: 'Classic Snake, StokeGames branded. Grow longer. Avoid yourself.',
    thumbnailUrl: '/images/twins-pixel-green-50pct.jpg',
    embedUrl: '/games/built-in/stokes-snake',
    type: 'builtin',
    categories: ['STRATEGY'],
    stokesScore: 68,
    alexRating: 3.5,
    alanRating: 3.0,
    alexReview: 'Nostalgic. Relaxing. Gets hard fast.',
    alanReview: 'Classic vibes.',
    fanScore: 71,
    totalPlays: 29_300,
    activePlayers: 31,
    badges: [],
    isInstantPlay: true,
    isMobile: true,
    isActive: true,
    isExclusive: false,
    maxScore: 500,
    releaseDate: '2024-01-28',
    createdAt: '2024-01-28T00:00:00Z',
  },
  {
    id: '7',
    slug: 'car-wash',
    title: 'Car Wash',
    description: 'Clean 10 different vehicles before time runs out — Lambo, limo, tank, boat, and more!',
    thumbnailUrl: '/images/twins-car-wash-50pct.png',
    embedUrl: '/games/built-in/car-wash',
    type: 'builtin',
    categories: ['CHAOTIC', 'SPEED'],
    stokesScore: 82,
    alexRating: 4.5,
    alanRating: 5.0,
    alexReview: 'I got 97% clean. Perfectionist mode.',
    alanReview: "I finished with 2 seconds to spare. Clean lambo = clean victory.",
    fanScore: 86,
    totalPlays: 48_700,
    activePlayers: 201,
    badges: ['NEW', 'HOT'],
    isInstantPlay: true,
    isMobile: true,
    isActive: true,
    isExclusive: false,
    maxScore: 10000,
    releaseDate: '2024-04-01',
    createdAt: '2024-04-01T00:00:00Z',
    videoUrl: 'https://www.youtube.com/watch?v=6EtuOTq5TmM',
  },
  {
    id: '8',
    slug: 'camo-game',
    title: 'Camo Game',
    description: 'You have 5 seconds to hide. Can you blend in before the scanner finds you?',
    thumbnailUrl: '/images/twins-camo-50pct.png',
    embedUrl: '/games/built-in/camo-game',
    type: 'builtin',
    categories: ['STRATEGY'],
    stokesScore: 79,
    alexRating: 4.0,
    alanRating: 4.5,
    alexReview: "I found the perfect hiding spot every round. It's instinct.",
    alanReview: 'Alan got caught on round 3 and refuses to talk about it.',
    fanScore: 81,
    totalPlays: 31_200,
    activePlayers: 98,
    badges: ['NEW', 'TWIN_PICK'],
    isInstantPlay: true,
    isMobile: true,
    isActive: true,
    isExclusive: false,
    maxScore: 2500,
    releaseDate: '2024-04-05',
    createdAt: '2024-04-05T00:00:00Z',
    videoUrl: 'https://www.youtube.com/watch?v=0hzcYyR9k9U',
  },
  {
    id: '9',
    slug: 'packing-peanuts',
    title: 'Packing Peanuts',
    description: 'Aim the leaf blower and fill the house with as many packing peanuts as possible!',
    thumbnailUrl: '/images/twins-packing-peanuts-50pct.png',
    embedUrl: '/games/built-in/packing-peanuts',
    type: 'builtin',
    categories: ['CHAOTIC'],
    stokesScore: 77,
    alexRating: 4.5,
    alanRating: 4.5,
    alexReview: 'This is exactly what we did. Except louder.',
    alanReview: 'I got 134 peanuts. The record is set.',
    fanScore: 80,
    totalPlays: 22_500,
    activePlayers: 67,
    badges: ['NEW'],
    isInstantPlay: true,
    isMobile: true,
    isActive: true,
    isExclusive: false,
    maxScore: 300,
    releaseDate: '2024-04-10',
    createdAt: '2024-04-10T00:00:00Z',
    videoUrl: 'https://www.youtube.com/watch?v=mVr8lw44zhc',
  },
]

export const SEED_LEADERBOARD: LeaderboardEntry[] = [
  { rank: 1, userId: 'u1', username: 'TwinSlayer99',    displayName: 'TwinSlayer99',    avatarUrl: null, rankTier: 'STOKEMASTER', score: 142_500, xp: 142_500, gamesPlayed: 12, createdAt: '2024-01-01Z' },
  { rank: 2, userId: 'u2', username: 'AlanIsGoated',    displayName: 'Alan Is Goated',  avatarUrl: null, rankTier: 'STOKEMASTER', score: 138_200, xp: 138_200, gamesPlayed: 10, createdAt: '2024-01-02Z' },
  { rank: 3, userId: 'u3', username: 'StokesOrDie',     displayName: 'StokesOrDie',     avatarUrl: null, rankTier: 'TWIN-LEVEL',  score: 124_800, xp: 124_800, gamesPlayed: 15, createdAt: '2024-01-03Z' },
  { rank: 4, userId: 'u4', username: 'FlappyKing',      displayName: 'FlappyKing',      avatarUrl: null, rankTier: 'TWIN-LEVEL',  score: 98_400,  xp: 98_400,  gamesPlayed: 9,  createdAt: '2024-01-04Z' },
  { rank: 5, userId: 'u5', username: 'ReactionGod',     displayName: 'Reaction God',    avatarUrl: null, rankTier: 'ELITE',       score: 76_200,  xp: 76_200,  gamesPlayed: 11, createdAt: '2024-01-05Z' },
  { rank: 6, userId: 'u6', username: 'StokesFan2024',   displayName: 'StokesFan2024',   avatarUrl: null, rankTier: 'ELITE',       score: 64_100,  xp: 64_100,  gamesPlayed: 8,  createdAt: '2024-01-06Z' },
  { rank: 7, userId: 'u7', username: 'alexfanatic',     displayName: 'alexfanatic',     avatarUrl: null, rankTier: 'CONTENDER',   score: 42_300,  xp: 42_300,  gamesPlayed: 7,  createdAt: '2024-01-07Z' },
  { rank: 8, userId: 'u8', username: 'GoldenRunner',    displayName: 'Golden Runner',   avatarUrl: null, rankTier: 'CONTENDER',   score: 38_700,  xp: 38_700,  gamesPlayed: 6,  createdAt: '2024-01-08Z' },
  { rank: 9, userId: 'u9', username: 'PixelWarrior',    displayName: 'Pixel Warrior',   avatarUrl: null, rankTier: 'CONTENDER',   score: 31_200,  xp: 31_200,  gamesPlayed: 5,  createdAt: '2024-01-09Z' },
  { rank: 10, userId: 'u10', username: 'NewChallenger', displayName: 'New Challenger',  avatarUrl: null, rankTier: 'ROOKIE',      score: 14_800,  xp: 14_800,  gamesPlayed: 3,  createdAt: '2024-01-10Z' },
]

export const SEED_CHALLENGE: Challenge = {
  id: 'c1',
  gameId: '1',
  title: 'Flappy Stokes Challenge',
  alexScore: 24_800,
  alanScore: 31_200,
  alexQuote: 'I got 24,800 on my first serious attempt. Top that.',
  alanQuote: "31,200. I told y'all I'm better. Prove me wrong.",
  prizeDescription: 'Stokes Twins signed merch pack + shoutout on stream',
  prizeImageUrl: null,
  startsAt: new Date(Date.now() - 86_400_000).toISOString(),
  endsAt: new Date(Date.now() + 5 * 86_400_000).toISOString(),
  isActive: true,
  winnerCount: 47,
  createdAt: new Date(Date.now() - 86_400_000).toISOString(),
  game: {
    id: '1',
    slug: 'flappy-stokes',
    title: 'Flappy Stokes',
    thumbnailUrl: '/images/twins-flappy-birds-50pct.jpg',
  },
}
